require "user.plugins"
require "user.keymaps"
require "user.alpha"
require "user.whichkey"
require "user.telescope"
require "user.lualine" 
require "user.nvim-tree"
require "user.toggleterm"
require "user.colorscheme"
require "user.treesitter"
require "user.numb"
require "user.gitsigns"
require "user.gitblame"
require "user.gitlinker"
require "user.autopairs"
require "user.comment"
require "user.notify"
require "user.lsp"
require "user.colorizer"
require "user.cmp"
require "user.nvim-web-icons"
require "user.options"


