require "user.plugins"
require "user.keymaps"
require "user.alpha"
require "user.whichkey"
require "user.telescope"
require "user.lualine"
require "user.blankline"
require "user.nvim-tree"
require "user.colorscheme"
require "user.lsp"
-- require "user.markdown"
-- require "user.bufferline"
require "user.numb"
-- require "user.gitlinker"
require "user.autopairs"
require "user.comment"
require "user.notify"
require "user.colorizer"
require "user.nvim-web-icons"
require "user.options"
